### ISSUE TITLE
The connection is broken and recovery is not possible.  The connection is marked by the client driver as unrecoverable.  No attempt was made to restore the connection.

### ISSUE THREAD

**Issue by guoxdxdxd** [1448376744/SqlBatis#2]
用scope注入服务
![1](https://user-images.githubusercontent.com/20676824/88495443-7c212580-cfec-11ea-8823-64b6af4643b3.png)
`
            services.AddScoped(typeof(DbContext), s =>
            {
                var context = new DbContext(new DbContextBuilder
                {
                    Connection = new SqlConnection(DelayQueueSqlServerOptions.ConnectionString),
                    DbContextType = DbContextType.SqlServer,
                });

                return context;
            });
`

然后有个定时任务，3秒执行一次，更新一条数据
![2](https://user-images.githubusercontent.com/20676824/88495473-95c26d00-cfec-11ea-824a-9f640bb5e33a.png)

更新的时候偶尔会出现异常
![3](https://user-images.githubusercontent.com/20676824/88495480-9c50e480-cfec-11ea-9907-7273be38d2bb.png)
`
System.Data.SqlClient.SqlException (0x80131904): The connection is broken and recovery is not possible.  The connection is marked by the client driver as unrecoverable.  No attempt was made to restore the connection.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlConnection.ValidateAndReconnect(Action beforeDisconnect, Int32 timeout)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQuery(AsyncCallback callback, Object stateObject)
`

这是我的打开方式不对吗？

**Comment by 1448376744** [comment]
连接对象无法跨线程使用，具体参阅你所使用的连接驱动文档，建议通过依赖容器子域的方式在每个线程上下文通过容器子域，来为每个线程创建数据库上下文实例……
